preload = /home/gabriel/.gemini/antigravity/brain/aa15e33c-c45f-466c-96c9-91a15999b940/tokyo_night_landscape_1776556326579.png
wallpaper = ,/home/gabriel/.gemini/antigravity/brain/aa15e33c-c45f-466c-96c9-91a15999b940/tokyo_night_landscape_1776556326579.png
splash = false
ipc = on
